# descriptor info for sankey view

# skillet name
name: sankey_2field_visual
# label used for menu selection
label: Kibana Visual Vega Sankey 2-field
description: Kibana Visual Vega Sankey 2-field visualization
dependency:
# type of device configuration
type: template
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: kibana
  collection: kibana

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: index
    description: index name (without * at the end)
    default: indexName
    type_hint: text
  - name: use_timeField
    description: data includes a date-time field
    default: 'yes'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'
  - name: timefield
    description: index time or date field
    default: timeField
    type_hint: text
    toggle_hint:
      source: use_timeField
      value: 'yes'
  - name: stack_1_field
    description: field for left side of sankey
    default: mystk1
    type_hint: text
    help_text: `.keyword` is auto appended during render to avoid aggregation errors
  - name: stack_1_label
    description: chart axis label for left side of sankey
    default: mystk1_label
    type_hint: text
  - name: stack_2_field
    description: field for right side of sankey
    default: mystk2
    type_hint: text
    help_text: `.keyword` is auto appended during render to avoid aggregation errors
  - name: stack_2_label
    description: chart axis label for right side of sankey
    default: mystk2_label
    type_hint: text
  - name: sankeyLines
    description: select if connecting lines based on doc counts or sum of field values
    default: doc_count
    type_hint: dropdown
    dd_list:
      - key: 'doc_count'
        value: docCount
      - key: 'sum field'
        value: sumField
  - name: sumField
    description: sum aggregation field for Sankey lines
    default: sum_field
    type_hint: text
    toggle_hint:
      source: sankeyLines
      value: sumField

snippets:
  - name: sankey_vega.txt
    file: sankey_vega.txt